version: '3'
services:

  postgres:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=jobsity

  api_service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: api_service
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    env_file:
      - ./api-service/.env.production

  stock_service:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    container_name: stock_service
    depends_on:
      - postgres
      - api_service
    ports:
      - "3000:3000"
    env_file:
      - ./stock-service/.env.production

