export enum HttpExceptionEnum {
  UNPROCESSED_ENTITY = 'UNPROCESSED_ENTITY',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  VALIDATION_EXCEPTION = 'VALIDATION_EXCEPTION',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
}
